# CI Build number is incremental and not related to actual version number of the product
version: '{build}'

image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true

before_build:
  - cmd: dotnet --version

build_script:
  - ps: |
        if ($env:APPVEYOR_REPO_TAG -eq $true) {
            $VersionSuffix = ""
        }
        else {
            $VersionSuffix = "ci" + $env:APPVEYOR_BUILD_NUMBER.PadLeft(4, "0") + "-" + $env:APPVEYOR_REPO_BRANCH
        }
  - ps: .\build.ps1 -VersionSuffix $VersionSuffix

test: off

artifacts:
  - path: artifacts\nuget\*.nupkg
    name: NuGet

# Deploy every successful build (except PRs) to development feed
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

deploy:
  # Create a GitHub release for every tag
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: "See milestone for changes"
    draft: true
    prerelease: true
    auth_token:
      secure: JU9H+A+WwAtz4Xkcd/50N239EiX1o7OpEnmtiQGayR+Zc2ZHF8xrcPMRelHyJwZL
    on:
      appveyor_repo_tag: true
