language: csharp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      mono: none
      dotnet: 3.1.402
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
            - dotnet-sdk-2.1

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - pwsh ./build.ps1
